### ISSUE TITLE
Crashing with no clue on trigger.

### ISSUE THREAD

**Issue by Magicloud** [taffybar/taffybar#414] opened 2018-09-05 16:53 UTC
**NOTE: If your issue is really a support request, please use the gitter channel to ask it instead of filing an issue https://gitter.im/taffybar/Lobby (REMOVE THIS IF NOT).**

**Describe the bug**
This bugs me for a while, I have to run `gdb` with it to catch the crash. Seems like it is more likely to occur after reboot. After about twice crashing, it can stay alive for quite a long time.
```
taffybar-linux-x86_64: internal error: evacuate: strange closure type 4693
    (GHC version 8.4.3 for x86_64_unknown_linux)
    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

Thread 1 "taffybar-linux-" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**To Reproduce**
No idea how.

**Expected behavior**
Stably running.

**Screenshots**
N/A

**Version information**
Taffybar version (or git sha if building from source): 09c600cdc1332619087a90c3958d5d1fd68a6067
Installation method (nix/stack/cabal/arch packages): cabal
Gtk version: 3.22.30

**Comment by IvanMalison** [comment] 2018-09-05 16:54
This is a duplicate of #358 . If you want stability it is recommended that you use ghc 8.2.x

**Closed** 2018-09-05 16:54 UTC
