### ISSUE TITLE
Incorrect alignment of context menus in tray

### ISSUE THREAD

**Issue by joshuap** [taffybar/taffybar#317] opened 2018-05-10 18:10 UTC
![image](https://user-images.githubusercontent.com/474649/39885842-8b47159c-5442-11e8-8273-23ab0adcba3e.png)

When I click on the dropbox icon, a context menu appears. It's almost entirely cut off by the edge of the screen, however. It would be ideal if it could detect the edge and flip the alignment of the menu to make it visible.

**Comment by IvanMalison** [comment] 2018-05-10 18:19
This one is a bit tricky because it actually needs to be fixed in https://github.com/taffybar/gtk-sni-tray .

An incremental step towards a complete solution might be to make the direction (from the icon widget) at which the context menu appears configurable.

Right now, that is actually hardcoded right here:
https://github.com/IvanMalison/gtk-sni-tray/blob/8a248da47a5ae39fd49b205c3a607f9b6dbe9c18/src/StatusNotifier/Tray.hs#L244

**Comment by IvanMalison** [comment] 2018-05-10 18:26
This issue is similar to #184

**Comment by IvanMalison** [comment] 2018-05-24 08:14
@joshuap This doesn't happen for me, are you using snitray or the old systray?

**Comment by joshuap** [comment] 2018-05-25 23:19
@IvanMalison I'm using snitray.

**Comment by IvanMalison** [comment] 2019-06-05 08:00
Closing because I can't reproduce. @joshuap feel free to reopen with a concrete repro.

**Closed by IvanMalison** 2019-06-05 08:00 UTC
Labels: bug, hard, help wanted, important
